### PR TITLE
Change private key that compathelper uses to COMPATHELPER_PRIV

### PR DESCRIPTION
**Pull request by ablaom**
@roland-KA 

After merging this you can follow the instructions for setting up the keys that are [here](https://juliaregistries.github.io/CompatHelper.jl/dev/#Creating-SSH-Key). 

If you get stuck, I'm happy to do it. I've struggled with setting these up in the past. Just thought you might want to learn how to do this for future projects...

### CODE REVIEW

**Comment by roland-KA** [comment]
I've managed to add a COMPATHELPER_PRIV key to my profile. 

But I couldn't add the deploy key to `TreeRecipe.jl`, because the repo is on JuliaAI. There I don't see the "Settings"-tab/button. On a repo on `roland-KA` it was no problem. Can you help me with this?

**Comment by ablaom** [comment]
I've made you administrator. You should now see "Settings" on on the left column links to  "Deploy Keys" and "Secrets".

**Comment by roland-KA** [comment]
Thanks, that worked!

But I've been running into another problem. Since I would like to use the CompatHelper also for other repos (like `OneRule.jl`), I've assigned the COMPATHELPER_PRIV key to both (OneRule and TreeRecipe). Then I've assigned the public key as a deploy key to `OneRule.jl` and noticed now, that I cannot reuse it for `TreeRecipe.jl` too.

But a key pair for each repo doesn't work either (then I get an error when using a second private key). How does that concept work with several repos in use?

**Comment by ablaom** [comment]
> But a key pair for each repo doesn't work either (then I get an error when using a second private key). How does that concept work with several repos in use?

Sorry but I don't understand. We have a separate private and public compat key pair for each individual repo in JuliaAI (and MLJ, which is part of alan-turing-institute). The keys are attached to repos and not individuals or organisations.

**Comment by roland-KA** [comment]
Ah now I know where the problem is. I followed the [CompatHelper guide](https://juliaregistries.github.io/CompatHelper.jl/dev/#Creating-SSH-Key). But I assumed that the GitHub secret (step 2 in "Create SSH Key") has to be added to my profile via "Settings -->  Codespaces --> New secrets" (as I didn't have a "Settings"-button in the repo anyway).

So this was the wrong place. I've put it now into the `TreeRecipe.jl`-repo (as well as the public key). I.e. everything should be ready now.

Perhaps you could have another look on it and if it's ok, merge the PR. Then I would rename the "main" branch to "master" and start the registration process.

**Comment by ablaom** [comment]
As far as I can tell, all is in order.

**Pull request merged**
